version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgreSQL
    profiles:
      - inventory
    restart: on-failure
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - inventory

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    profiles:
      - inventory
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    environment:
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_URL: ${POSTGRES_URL}
    volumes:
      - ./flyway-service/sql_versions:/flyway/sql
    depends_on:
      - postgres
    networks:
      - inventory

  network-device-inventory:
    image: lsefiane/network-device-inventory:latest
    container_name: network-device-inventory
    profiles:
      - inventory
    restart: on-failure
    ports:
      - ${NETWORK_DEVICE_INVENTORY_PORT}:${NETWORK_DEVICE_INVENTORY_PORT}
    healthcheck:
      test: wget --no-verbose --spider http://localhost:8080/inventory/api/actuator/health || exit 1
      interval: 25s
      timeout: 3s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_DRIVERCLASSNAME: ${SPRING_DATASOURCE_DRIVERCLASSNAME}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_INITIALIZATION_MODE: ${SPRING_DATASOURCE_INITIALIZATION_MODE}
      SPRING_CLOUD_CONSUL_ENABLED: ${SPRING_CLOUD_CONSUL_ENABLED}
      SPRING_CLOUD_CONSUL_HOST: ${SPRING_CLOUD_CONSUL_HOST}
      SPRING_CLOUD_CONSUL_PORT: ${SPRING_CLOUD_CONSUL_PORT}
      SPRING_CLOUD_CONSUL_DISCOVERY_HEALTHCHECKURL: ${SPRING_CLOUD_CONSUL_DISCOVERY_HEALTHCHECKURL}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      MANAGEMENT_METRICS_TAGS_APPLICATION: ${SPRING_APPLICATION_NAME}

    depends_on:
      - postgres
      - consul
    networks:
      - inventory

  consul:
    image: consul:latest
    container_name: consul
    profiles:
      - inventory
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    restart: always
    ports:
      - ${CONSUL_PORT}:${CONSUL_PORT}
    environment:
      - CONSUL_BIND_INTERFACE=${CONSUL_BIND_INTERFACE}
    networks:
      - inventory

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    profiles:
      - monitoring
    restart: on-failure
    expose:
      - ${POSTGRES_EXPORTER_PORT}
    depends_on:
      - postgres
    environment:
      DATA_SOURCE_NAME: ${POSTGRES_EXPORTER_DATA_SOURCE_NAME}
    networks:
      - inventory

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles:
      - monitoring
    restart: unless-stopped
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - ./prometheus-service:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - node-exporter
      - postgres-exporter
      - cadvisor
      - alertmanager
      - consul
    networks:
      - inventory
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    profiles:
      - monitoring
    restart: unless-stopped
    expose:
      - ${ALERT_MANAGER_PORT}
    volumes:
      - ./alertmanager-service:/etc/alertmanager
      - alertmanager-data:/data
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--log.level=debug'
    networks:
      - monitoring


  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    profiles:
      - monitoring
    privileged: true
    restart: on-failure
    expose:
      - ${NODE_EXPORTER_PORT}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    profiles:
      - monitoring
    restart: on-failure
    expose:
      - ${CADVISOR_CONTAINER_PORT}
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    profiles:
      - monitoring
    restart: unless-stopped
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    depends_on:
      - prometheus
    volumes:
      - ./grafana-service/provisioning:/etc/grafana/provisioning
      - ./grafana-service/grafana.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: ${GRAFANA_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH}
    networks:
      - monitoring

volumes:
  pgdata:
  prometheus-data:
  alertmanager-data:
  grafana-storage:

networks:
  inventory:
  monitoring: