groups:
  - name: alerts
    rules:
      # Alert for any instance that is unreachable for 1 minutes.
      - alert: InstanceDown
        # Condition for alerting
        expr: up == 0
        for: 1m
        # Labels - additional labels to be attached to the alert
        labels:
          severity: critical
        # Annotation - additional informational labels to store more information
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."