# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Partner Orb
orbs:
  snyk: snyk/snyk@1.1.2
  sonarcloud: sonarsource/sonarcloud@1.1.0

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

executors:
  docker-publisher:
    docker:
      - image: cimg/node:18.2.0

jobs:
  sonar-cloud:
    parameters:
      image:
        type: string
        default: cimg/openjdk:11.0.13
      command:
        type: string
      working_directory:
        type: string
    docker:
      - image: <<parameters.image>>
    working_directory: <<parameters.working_directory>>
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: <<parameters.command>>
      - store_artifacts:
          path: <<parameters.working_directory>>/target

  maven-build:
    parameters:
      image:
        type: string
        default: cimg/openjdk:11.0.13
      working_directory:
        type: string
      checkout_path:
        type: string
      prefix_key:
        type: string
    docker:
      - image: <<parameters.image>>
    working_directory: <<parameters.working_directory>>
    steps:
      - checkout:
          path: <<parameters.checkout_path>>
      - restore_cache:
          key: <<parameters.prefix_key>>-{{ checksum "pom.xml" }}
      - run:
          name: mvn dependency go offline
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: <<parameters.prefix_key>>-{{ checksum "pom.xml" }}
      - run:
          name: mvn clean install
          command: mvn clean install
      - store_test_results:
          path: <<parameters.working_directory>>/target/surefire-reports
      - store_artifacts:
          path: <<parameters.working_directory>>/target/<<parameters.prefix_key>>-0.0.1-SNAPSHOT.jar
      - persist_to_workspace:
          root: <<parameters.working_directory>>/target
          paths:
            - <<parameters.prefix_key>>-0.0.1-SNAPSHOT.jar

  maven-docker-build:
    parameters:
      working_directory:
        type: string
      checkout_path:
        type: string
      docker_image:
        type: string
      prefix_key:
        type: string
    executor: docker-publisher
    working_directory: <<parameters.working_directory>>
    steps:
      - checkout:
          path: <<parameters.checkout_path>>
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: <<parameters.working_directory>>/target
      - run:
          name: Build Docker image
          command: docker build <<parameters.docker_image>> .
      - run:
          name: Archive Docker image
          command: docker save --output <<parameters.prefix_key>>.tar <<parameters.docker_image>>
      - persist_to_workspace:
          root: .
          paths:
            - ./<<parameters.prefix_key>>.tar

  docker-build:
    parameters:
      working_directory:
        type: string
      checkout_path:
        type: string
      docker_image:
        type: string
      prefix_key:
        type: string
    executor: docker-publisher
    working_directory: <<parameters.working_directory>>
    steps:
      - checkout:
          path: <<parameters.checkout_path>>
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t <<parameters.docker_image>>:latest -t <<parameters.docker_image>>:$CIRCLE_SHA1 .
      - run:
          name: Archive Docker image
          command: docker save --output <<parameters.prefix_key>>.tar <<parameters.docker_image>>:latest <<parameters.docker_image>>:$CIRCLE_SHA1
      - persist_to_workspace:
          root: .
          paths:
            - ./<<parameters.prefix_key>>.tar

  snyk-scan:
    parameters:
      archive:
        type: string
      image:
        type: string
    executor: docker-publisher
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run:
          command: docker load -i <<parameters.archive>>
      - snyk/scan:
          severity-threshold: high
          docker-image-name: <<parameters.image>>
          fail-on-issues: true

  docker-compose:
    executor: docker-publisher
    parameters:
      working_directory:
        type: string
      command:
        type: string
      checkout_path:
        type: string
    working_directory: <<parameters.working_directory>>
    steps:
      - checkout:
          path: <<parameters.checkout_path>>
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image(s)
          command: |
            for f in /tmp/workspace/*.tar; do
              cat $f | docker load
            done
      - run:
          name : Docker Compose UP
          command: <<parameters.command>>

  docker-publish:
    executor: docker-publisher
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image(s)
          command: |
            for f in /tmp/workspace/*.tar; do
              cat $f | docker load
            done
      - run:
          name: Login to DockerHub
          command: |
            echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin
      - run:
          name: Publish Docker image(s)
          command: |
            for image_name in $(docker images --format="{{.Repository}}:{{.Tag}}")
            do
              docker push $image_name
            done
      - run:
          name: Logout from DockerHub
          command: docker logout
            


workflows:
  network-device-inventory-development-workflow:
    jobs:
      - sonar-cloud:
          name: sonar-cloud-inventory
          working_directory: ~/network-device-inventory
          command: mvn verify sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.host.url=$HOST_URL -Dsonar.organization=$ORGANIZATION
          context:
            - SonarCloud
      - maven-build:
          name: maven-build-inventory
          working_directory: ~/network-device-inventory/network-device-inventory-service
          checkout_path: ~/network-device-inventory
          prefix_key: network-device-inventory-service
          requires:
            - sonar-cloud-inventory
      - maven-docker-build:
          name: docker-build-inventory
          working_directory: ~/network-device-inventory/network-device-inventory-service
          checkout_path: ~/network-device-inventory
          docker_image: $CI_REGISTRY_USER/$NETWORK_DEVICE_INVENTORY_SERVICE
          prefix_key: network-device-inventory-service
          requires:
            - maven-build-inventory
      - snyk-scan:
          name: snyk-scan-inventory
          archive: network-device-inventory-service.tar
          image: $CI_REGISTRY_USER/$NETWORK_DEVICE_INVENTORY_SERVICE
          requires:
            - docker-build-inventory