version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgreSQL
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservice

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    environment:
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_URL: ${POSTGRES_URL}
    volumes:
      - ./flyway/sql_versions:/flyway/sql
    depends_on:
      - postgres
    networks:
      - microservice

  network-device-inventory:
    image: lsefiane/network-device-inventory:latest
    container_name: network-device-inventory
    restart: on-failure
    ports:
      - ${NETWORK_DEVICE_INVENTORY_PORT}:${NETWORK_DEVICE_INVENTORY_PORT}
    healthcheck:
      test: wget --no-verbose --spider http://localhost:8080/inventory/api/actuator/health || exit 1
      interval: 25s
      timeout: 3s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_DRIVERCLASSNAME: ${SPRING_DATASOURCE_DRIVERCLASSNAME}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_INITIALIZATION_MODE: ${SPRING_DATASOURCE_INITIALIZATION_MODE}
    depends_on:
      - postgres
    networks:
      - microservice

volumes:
  pgdata:

networks:
  microservice: